config/routes.rb
Rails.application.routes.draw do
  get 'deliveries/create'
  root to: 'pages#home'
  get '/pages/confirmation', to: 'pages#confirmation', as: "confirmation"
  devise_for :users
  get '/dashboard', to: 'pages#dashboard'
  get '/summary', to: 'pages#summary'
  resources :shops
  resources :products, only: [:update, :edit, :destroy, :new, :create] do
    resources :cart_items, only: [:create]
  end  
  resources :cart_items, only: [:update, :destroy] do
    member do
      patch "increase"
    end
  end
  resources :carts, only: [:show, :update] do
    resources :deliveries, only: :create # patch "/increase", 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/shop.rb
class Shop < ApplicationRecord
  has_many :products, dependent: :destroy
  belongs_to :user
  has_many :carts
  has_many :users, through: :carts
  validates :name, uniqueness: true, presence: true
  validates :address, uniqueness: true, presence: true
  validates :phone_number, uniqueness: true, presence: true
  validates :email, uniqueness: true, presence: true
  has_one_attached :photo
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  scope :with_category, ->(category) { joins(:products).merge(Product.where(category: category)).distinct }


  def distance_from(user)
    if latitude.blank? || longitude.blank?
      return "Direccion no disponible"
    else
      distance = self.distance_to([user.latitude, user.longitude])
      distance_value = (distance < 1) ? (distance * 1000).to_i  : distance.to_i
      if distance < 1 
        distance_unit = distance_value == 1 ? "mt": "mts"
      else
       distance_unit =  distance_value == 1 ? "km": "kms"
      end
      return "#{distance_value} #{distance_unit}"
    end
  end
end

app/controllers/shops_controller.rb
class ShopsController < ApplicationController
skip_before_action :authenticate_user!, only: [ :index ]

  def index
    @category = params[:category]
    if @category.present?
      @products = Product.where(category: @category)
      @shops = policy_scope(Shop).with_category(@category)
    else
      @shops = policy_scope(Shop)
      @products = Product.order("RANDOM()").first(10)
    end
      @destacados = Shop.joins(:products).distinct.select('shops.*, COUNT(products.*) AS products_count').group('shops.id').order("products_count DESC")
     @cercanos = policy_scope(Shop).near([current_user.latitude, current_user.longitude], 5) if user_signed_in?
  end

  def show
    @shop = Shop.find(params[:id])
    authorize @shop
    @products = Product.where(shop_id: @shop.id)
    @markers = [{lat: @shop.latitude,
      lng: @shop.longitude,
      infoWindow: render_to_string(partial: "info_window", locals: { shop: @shop })
    }]
  end

  def new
    @shop = Shop.new
    authorize @shop
  end

  def create
    @shop = Shop.new(shop_params)
    if @shop.save
      flash[:notice] = "Creado con exito"
      redirect_to @shop
    else
      flash[:error] = "Error al crear el comercio"
      render 'new'
    end
    authorize @shop
  end

  def edit
    @shop = Shop.find(params[:id])
    authorize @shop
  end

  def update
  @shop = Shop.find(params[:id])
    if @shop.update_attributes(shop_params)
      flash[:notice] = "Actualizado con exito"
      redirect_to @shop
    else
      flash[:notice] = "Intenta nuevamente"
      render 'edit'
    end
    authorize @shop
  end

  def destroy
    @shop = Shop.find(params[:id])
    authorize @shop
    @shop.destroy
    redirect_to shops_path
  end

private
  def shop_params
    params.require(:shop).permit(:name, :address, :email, :phone_number, :user_id, :photo)
  end
end

app/views/shops/_info_window.html.erb
<h4><%= @shop.name %></h2>
<p id="pedelmap"><%= @shop.address %></p>

app/views/shops/edit.html.erb
<h1>Shops#edit</h1>
<p>Find me in app/views/shops/edit.html.erb</p>
<%= simple_form_for @shop do |f| %>
<%= f.input :name, label:"Nombre:", required: false %>
<%= f.input :address, label:"Direccion:", required: false %>
<%= f.input :email, label:"Email:", required: false %>		 
<%= f.input :phone_number, label:"Telefono:", required: false %>
<%= f.input :photo, as: :file, label:"Agregá una imagen:", required: false %>
<%= f.hidden_field :user_id, :value => current_user.id%>
<%= f.button :submit, label:"Agregar", class: "btn btn-outline-dark" %>
<%= link_to "Restablecer", "", class: "btn btn-outline-warning"%>
<% end %>

app/views/shops/index.html.erb
<%= render 'shared/banner_index' %>
<%#= render 'shared/banner' %>
<div class="bg-white">

  <div class="d-flex justify-content-center container-fluid mb-5 ">
    <div class="icon-categories bt-1 d-flex justify-content-around p-3 p-md-2 ">
      <% Product.category_options_for_select.each do |category| %>
        <%= link_to shops_path(category: category), class:"category-item" do %>
          <%= cl_image_tag( category , crop: :fill, class:"rounded",style:"object-fit: cover") %>
          <p id="p-icons" class="d-none d-sm-block"><%= category.capitalize %></p>
        <% end %>
      <% end %>
    </div>
  </div>
  <%# SI EL USER ESTA CONECTADO LE MUESTRO CERCA TUYO!!  %>
  <% if user_signed_in? %>
    <div class="wrapper_index">
      <h2 class="text-left ml-4 ">Platones diarios</h2>
      <div class="cards_index dragscroll">
        <% @products.each do |product| %>
            <div style="height: 400px; min-width:350px; max-width:350px;" class="mr-3 d-flex flex-column border rounded shadow">
              <% if product.photo.attached? %>
                <div style="background-image: url(<%= cl_image_path(product.photo.key) %>); background-size: cover; object-fit: cover;" class=" rounded flex-grow-1  position-relative" >
              <% else %>
                <div style="background-image: url('https://picsum.photos/200/200'); background-size: cover;" class=" rounded flex-grow-1  position-relative" >
              <% end %>
              <% if current_user.active_cart.nil? %>
                    <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, class:"m-0 h6 bg-primary rounded px-3 py-1 position-absolute border text-white border-white", style:"bottom:10px; right: 10px;" %>
                <% else %>
                  <% if current_user.active_cart.shop == @shop %>
                    <% if cart_item = current_user.active_cart.cart_items.find { |item| item.product == product } %>
                      <%= link_to "Agregar otro", increase_cart_item_path(cart_item), method: :PATCH, class:"m-0 h6 bg-primary rounded px-3 py-1 position-absolute border text-white border-white",style:"bottom:10px; right: 10px;"%>
                    <% else %>
                      <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, class:"m-0 h6 bg-primary rounded px-3 py-1 position-absolute border text-white border-white", style:"bottom:10px; right: 10px;"%>
                    <% end %>
                  <% else %>
                    <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, data: { confirm: 'Tu carrito tiene productos de otro shop, si deseas continuar seran removidos!' }, class:"m-0 h6 bg-primary rounded px-3 py-1 position-absolute border text-white border-white", style:"bottom:10px; right: 10px;" %>
                  <% end %>
                <% end %>
            </div>
            <div class="flex-grow-0 p-3">
              <h2 class="m-0 h4 text-center"> <%= product.name %></h2>
              <h3 class="text-center m-0 h6 text-uppercase text-primary mt-1 "> <%= product.shop.name.truncate(20, separator: '') %></h3>
              <p class="m-0 mt-3 h6 font-weight-light text-center"> <%= product.description.truncate(35) %></p>
                <div class="d-flex justify-content-between mt-3">
                  <div class="d-flex align-items-center">
                    <span class="font-weight-bold mr-1"> <%= rand(3..5) %>.0</span>
                    <i class="fas fa-star text-primary"></i>
                    <div class="text-muted ml-2">(<i class="fas fa-walking pr-1"></i><span><%= product.shop.distance_from(current_user) %>)</span></div>
                    </div>
                  <div>
                  <strike class="text-muted pr-2">$<%= product.previous_price %></strike><span class="font-weight-bold">$<%= product.unit_price %></span>
                </div>
            </div>
          </div>
        </div>
      <% end %>
    </div>
    </div>
    <%# Locales cercanos !!  %>
    <div class="wrapper_index">
      <h2 class="text-left ml-4 pb-4">Locales cercanos</h2>
      <div class="cards_index dragscroll">
        <% @cercanos.each do |shop| %>
          <%= link_to shop_path(shop) do %>
            <div class="card-index-shop">
                <% if shop.photo.attached? %>
                  <%= cl_image_tag shop.photo.key, height:300, width:300, crop: :fill %>
                <% else %>
                  <%= cl_image_tag("mojito_baggco", height:300, width:300, crop: :fill) %>
                <% end %>
              <div class="card-shop-infos position-relative">

                <h4 class="text-center"><%= shop.name %> </h4>
                  <div class="rating-shop">
                    <% if shop.rating.nil? %>
                      <% 5.times do %>
                        <i class="far fa-star text-primary"></i>
                      <% end %>
                    <% else %>
                      <% shop.rating.times do  %>
                        <i class="fas fa-star text-primary"></i>
                      <% end %>
                      <% (5 - shop.rating).times do %>
                        <i class="far fa-star text-primary"></i>
                      <% end %>
                    <% end %>
                  </div>
                  <p class=" m-0 d-flex justify-content-center"> <i class="fas fa-map-marker" id="icono_localizacion"></i> <%=shop.distance_from(current_user) %></p>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>
  <% end %>


    <%# DESTACADOS !! ( SE MUESTRA SIEMPRE) %>
    <div class="wrapper_index mb-5">
      <h2 class="text-left ml-4 pb-4">Destacados</h2>
      <div class="cards_index dragscroll">
        <% @destacados.each do |shop| %>
          <%= link_to shop_path(shop) do %>
            <div class="card-index-shop">
                <% if shop.photo.attached? %>
                  <%= cl_image_tag shop.photo.key, height:300, width:300, crop: :fill %>
                <% else %>
                  <%= cl_image_tag("mojito_baggco", height:300, width:300, crop: :fill) %>
                <% end %>
              <div class="card-shop-infos text-align-right">
                <div>
                <h4><%= shop.name %> </h4>
                  <div class="rating-shop ">
                      <% if shop.rating.nil? %>
                        <% 5.times do %>
                          <i class="far fa-star text-primary"></i>
                        <% end %>
                      <% else %>
                        <% shop.rating.times do  %>
                          <i class="fas fa-star text-primary"></i>
                        <% end %>
                        <% (5 - shop.rating).times do %>
                          <i class="far fa-star text-primary"></i>
                        <% end %>
                      <% end %>
                  </div>
                  <p class=" m-0 d-flex justify-content-center"> <i class="fas fa-map-marker" id="icono_localizacion"></i> <%=shop.address.first(25) %></p>
                </div>
              </div>
            </div>
          <% end %>
        <% end %>
      </div>
    </div>

</div>

app/views/shops/new.html.erb
<div class=".container bg-white rounded mt-5 p-4 shadow-sm" id="new-product">
  <h3 class="d-flex justify-content-center py-3">Nuevo Local</h3>
  <%= simple_form_for @shop do |f| %>
  <%= f.input :name, label:"Nombre:", required: false %>
  <%= f.input :address, input_html: { id: "address-input" }, label:"Direccion:", required: false %>
  <%= f.input :email, label:"Email:", required: false %>
  <%= f.input :phone_number, label:"Telefono:", required: false %>
  <%= f.input :photo, as: :file, label:"Agregá una imagen:", required: false %>
  <%= f.hidden_field :user_id, :value => current_user.id%>
  <%= f.button :submit, "Agregar", class: "btn btn-primary " %>
  <% end %>
</div>

app/views/shops/show.html.erb
<% if @products.first.photo.attached? %>
  <div class="banner-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.7)), url(<%=cl_image_path @products.first.photo.key %>)">
    <div class="container">
      <h1 class="text-center"><%= @shop.name %></h1>
    </div>
  </div>
<% else %>
  <div class="banner-show mb-4" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(<%=cl_image_path "nodisponible" %>)">
    <div class="container">
      <h1 class=""><%= @shop.name %></h1>
    </div>
  </div>
<% end %>
<div class="container">
  <div class="row"> 
    <div class="col-12 col-md-6">
      <div class="platos">
        <div class="row justify-content-center">
          <% @products.each do |product| %>
            <div class="col-12 col-md-12">
              <div class="card-product">
                <%= cl_image_tag product.photo.key, height:350, width:350, crop: :fill %>
                <div class="card-product-infos d-flex flex-column justify-content-between">
                  <div class="d-flex justify-content-between">
                    <div>
                      <h2><%= product.name %></h2>
                      <p><%= product.description %></p>
                    </div>
                    <div class="d-flex flex-column">
                      <span class="price-product">$ <%= product.previous_price %></span>
                      <span class="offer-product">$<%= product.unit_price %></span>
                    </div>
                  </div>
                  <div class="text-center">
                    <% if current_user.active_cart.nil? %>
                        <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, class:"btn btn-primary btn-sm rounded"%>
                    <% else %>
                      <% if current_user.active_cart.shop == @shop %>
                        <% if cart_item = current_user.active_cart.cart_items.find { |item| item.product == product } %>
                          <%= link_to "Agregar otro", increase_cart_item_path(cart_item), method: :PATCH, class:"btn btn-primary btn-sm rounded"%>
                        <% else %>
                          <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, class:"btn btn-primary btn-sm rounded"%>
                        <% end %>
                      <% else %>
                        <%= link_to "Agregar al Carrito", product_cart_items_path(product), method: :POST, data: { confirm: 'Tu carrito tiene productos de otro shop, si deseas continuar seran removidos!' }, class:"btn btn-primary btn-sm rounded"%>
                      <% end %>
                    <% end %>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
        </div>
      </div>
    </div>
    <div class="col-12 col-md-6 ">
      <div class="rounded h-100">
        <div id="map"
        style="width: 100%; height: 100%;"
        data-markers="<%= @markers.to_json %>"
        data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>">
        </div>
      </div>
    </div>
  </div>
  <div class="d-flex justify-content-center mb-2">
      <%= link_to "Volver", shops_path, class:" btn btn-info btn-md rounded mt-4"  %>
  </div>
</div>    