config/routes.rb
Rails.application.routes.draw do
  get 'deliveries/create'
  root to: 'pages#home'
  get '/pages/confirmation', to: 'pages#confirmation', as: "confirmation"
  devise_for :users
  get '/dashboard', to: 'pages#dashboard'
  get '/summary', to: 'pages#summary'
  resources :shops
  resources :products, only: [:update, :edit, :destroy, :new, :create] do
    resources :cart_items, only: [:create]
  end  
  resources :cart_items, only: [:update, :destroy] do
    member do
      patch "increase"
    end
  end
  resources :carts, only: [:show, :update] do
    resources :deliveries, only: :create # patch "/increase", 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/shared/_banner.html.erb
<div class="d-flex align-items-end align-items-md-center px-0 px-md-5 pb-3" style="height:60vh; background-size:cover; background-image: linear-gradient(-270deg, rgba(0,0,0,0.4),rgba(255,255,255,0.1)), url(https://res.cloudinary.com/ayegora/image/upload/v1597183115/banner_tu2wcu.png)">
   <div class="d-flex justify-content-center justify-content-md-start">
      <div class="mx-0 mx-md-5 w-100 w-sm-50 w-md-25">
        <h1 class="text-center text-md-left m-0 text-white mb-4 mb-md-4"><strong> La buena comida hay que probarla, no tirarla. </strong></h1>
        <p class="h5 text-center text-md-left font-weight-lighter text-white mb-5 mb-md-4">Vinimos para ayudarte a ahorrar más y contaminar menos.</p>
        <div class="d-flex flex-column flex-md-row px-4 p-md-0"> 
          <%= link_to "Explorá Platón", shops_path,  class:"bg-white px-2 p-1 py-md-3 px-md-4 border-primary rounded-pill text-center m-0 mb-1 mb-md-0 mr-md-3 mt-5 mt-md-0 h5 text-decoration-none"%>
          <%= link_to "Registá tu local", shops_path,  class:"bg-primary d-none d-md-block px-2 p-1 py-md-3 px-md-4 border-white text-white rounded-pill text-center m-0 mr-md-3 h5 text-decoration-none", data: { toggle:"modal", target:"#exampleModal" } %>
        </div>
      </div>
   </div>
</div>

      <%= link_to "Registá tu local", shops_path,  class:"bg-primary d-block d-md-none px-2 p-1 p-md-3 border-white text-white rounded-pill text-center mt-3 mx-3 mr-md-3 h5 text-decoration-none", data: { toggle:"modal", target:"#exampleModal" } %>


  <%# MODAL!!!!!!!!!!!!!!!!!!!! %>
  <div class="modal fade" id="exampleModal" tabindex="-1" role="dialog" aria-labelledby="exampleModalLabel" aria-hidden="true">
  <div class="modal-dialog" role="document">
    <div class="modal-content rounded bg-warning">
      <div class="modal-header">
        <h5 class="modal-title" id="exampleModalLabel">Registra tu local en Platón</h5>
        <button type="button" class="close" data-dismiss="modal" aria-label="Close">
          <span aria-hidden="true">&times;</span>
        </button>
      </div>
      <div class="modal-body">
       <div class="form-inputs">
        <form>
          <div class="form-group">
            <label for="exampleInputPassword1">Ingresa el nombre de tu local:</label>
            <input type="text" class="form-control" id="exampleInputPassword1"placeholder="Salva El Planeta">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Dirección:</label>
            <input type="text" class="form-control" id="address-input" placeholder="Ej: Calle 43 771, La Plata, Argentina">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Numero de teléfono:</label>
            <input type="text" class="form-control" id="exampleInputPassword1" placeholder="Ej: 011-1578525">
          </div>
          <div class="form-group">
            <label for="exampleInputPassword1">Email:</label>
            <input type="text" class="form-control" id="exampleInputPassword1" placeholder="salvaelplaneta@platones.com">
          </div>
          <button type="submit" class="btn btn-primary">Enviar datos</button>
        </form>
       </div>
      </div>
    
      </div>
    </div>
  </div>

app/views/shared/_banner_index.html.erb
<div class="banner-index " id="banner-index" style="background-image: linear-gradient(rgba(0,0,0,0.4),rgba(0,0,0,0.4)), url(https://images.pexels.com/photos/315755/pexels-photo-315755.jpeg?auto=compress&cs=tinysrgb&dpr=2&w=500)">
  <div class="container div-banner-index">
    <h1 class="text-center" id="h1-banner-index">Quien comparte su comida no está solo en la vida</h1>
  </div>
</div>

app/views/shared/_card.html.erb
<div class="container">
  <div class="card" style="background-image:url(https://tecnohotelnews.com/wp-content/uploads/2018/04/siete-claves-para-ofrecer-platos-saludables-atractivos-a-los-comensales.jpg);">
  
  </div>
  <div class="descripcion">
    <div class="rating">
      ESTRELLITAS
    </div>
    <h4>PLATO</h4>
    <p>RESTAURANT</p>  
  </div>
</div>

app/views/shared/_flashes.html.erb
<% if notice %>
  <div class="alert alert-info alert-dismissible fade show m-1" role="alert">
    <%= notice %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>
<% if alert %>
  <div class="alert alert-warning alert-dismissible fade show m-1" role="alert">
    <%= alert %>
    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
      <span aria-hidden="true">&times;</span>
    </button>
  </div>
<% end %>

app/views/shared/_footer.html.erb
<div id="footer" class="footer">
  <div class="footer-links">
    <a href="https://www.instagram.com/platonarg/"><i class="fab fa-instagram"></i></a>
    <a href="#"><i class="fab fa-linkedin"></i></a>
  </div>
    <div class="footer-copyright">
      © Platon 2020
    </div>
</div>

app/views/shared/_navbar.html.erb
  <div class="navbar navbar-expand-sm <%=local_assigns[:home] ? "navbar-dark bg-transparent position-absolute w-100 " : "navbar-light" %> navbar-lewagon">
  <%# Titulo (logo) %>
  
  <%= link_to "/shops", class: "nav-link loguito" do %>
    <% if local_assigns[:home] %>
      <%= cl_image_tag("logo_bikvoh") %>
    <% else %>
      <%= cl_image_tag("logonegro_rkg2il") %>
    <% end %>
  <% end %>
  
  <div class="carritocel">
    <% if user_signed_in? %>
      <% if !current_user.carts.empty? && !current_user.active_cart.nil?  %>
        <%= link_to cart_path(current_user.carts.last), class: "nav-link mr-2" do %>
          <span class="carrito">
            <i class="fas fa-shopping-cart"></i>
            <% if !current_user.active_cart.nil? && current_user.active_cart.has_items? %>
              <span class="number"> <%= current_user.active_cart.number_of_items %> </span>
            <% end %>
          </span>
        <% end %>
      <% else %>
        <i class="fas fa-shopping-cart mt-2 mr-4"></i>
      <% end %>
    <% end %>
  </div>


  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
    <%# CUANDO EL USUARIO ESTA LOGEADO  %>
    <% if user_signed_in? %>
        <li class="nav-item active mr-2">
            <% if !current_user.carts.empty? && !current_user.active_cart.nil?  %>
              <%= link_to cart_path(current_user.carts.last), class: "nav-link mr-2" do %>
                <span class="carrito">
                  <i class="fas fa-shopping-cart"></i>
                  <% if !current_user.active_cart.nil? && current_user.active_cart.has_items? %>
                    <span class="number"> <%= current_user.active_cart.number_of_items %> </span>
                  <% end %>
                </span>
              <% end %>
            <% else %>
              <i class="fas fa-shopping-cart mt-2 mr-4"></i>
            <% end %>
        </li>
        <li class="nav-item active">
          <%= link_to "Inicio", "/shops", class: "nav-link mr-2" %>
        </li>
        

        <%# Si el user logeado es OWNER MOSTRA ESTO %>
        <% if current_user.role == "owner"  %>
        <li class="nav-item active">
           <%= link_to "Mi Local", dashboard_path , class: "nav-link" %>
         </li>
           <%= link_to "Agregar Productos", new_product_path, class: "nav-link" %>
         <li class="nav-item active">
         </li>
        <% end %>

        <%# DROPDOWN %>
        <li class="nav-item dropdown">
          <% if current_user.photo.present? %>
            <%= cl_image_tag(current_user.photo.key, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% else %>
            <%= cl_image_tag("avatar", :radius=>"max", :width=>100, class: "avatar dropdown-toggle", id: "navbarDropdown", data: { toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false) %>
          <% end %>
          <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
            <%# Si el user logeado es OWNER MOSTRA ESTO %>
            <% if current_user.role == "owner"  %>
              <%= link_to "Agregar Productos", new_product_path, class: "dropdown-item" %>
              <%= link_to "Mi Local",dashboard_path, class: "dropdown-item" %>
              <%= link_to "Resumen de ventas", summary_path, class:"dropdown-item" %>

            <% end %>
            <%# ESTO LO VEN TODOS LOS users %>
             <%= link_to "Editar mis datos", edit_user_registration_path(current_user), class: "dropdown-item" %>
            <%= link_to "Cerrar sesión", destroy_user_session_path, method: :delete, class: "dropdown-item" %>
          </div>
        </li>

      <% else %> <%# CUANDO EL USUARIO NO ESTA LOGEADO  %>
        <li class="nav-item">
          <i class="fas fa-search nav-link mt-1"></i>
        </li>
        <li class="nav-item">
          <%= link_to "Nosotros", new_user_session_path, class: "nav-link letrablanca mr-2 ml-2" %>
        </li>

        <li class="nav-item">
          <%= link_to "Ayuda", new_user_session_path, class: "nav-link letrablanca mr-2 ml-2" %>
        </li>

        <li class="nav-item">
          <%= link_to "Iniciar sesión", new_user_session_path, class: "nav-link letrablanca mr-2 ml-2" %>
        </li>
        <li class="nav-item">
        <% if local_assigns[:home] %>
          <%= link_to "Quiero registrarme",  new_user_registration_path, class: "btn btn-outline-light botonarriba mr-2 ml-2" %>
        <% else %>
          <%= link_to "Quiero registrarme",  new_user_registration_path, class: "btn btn-outline-dark botonarriba mr-2 ml-2" %>
        </li>
        <% end %>
      <% end %>
    </ul>
  </div>
</div>