config/routes.rb
Rails.application.routes.draw do
  get 'deliveries/create'
  root to: 'pages#home'
  get '/pages/confirmation', to: 'pages#confirmation', as: "confirmation"
  devise_for :users
  get '/dashboard', to: 'pages#dashboard'
  get '/summary', to: 'pages#summary'
  resources :shops
  resources :products, only: [:update, :edit, :destroy, :new, :create] do
    resources :cart_items, only: [:create]
  end  
  resources :cart_items, only: [:update, :destroy] do
    member do
      patch "increase"
    end
  end
  resources :carts, only: [:show, :update] do
    resources :deliveries, only: :create # patch "/increase", 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/views/pages/confirmation.html.erb
<div class="contiene-todo container bg-white mt-5 shadow-lg">
  <div class="d-flex-column">
    <div class="contenedor-imagen text-center">
      <img src="https://mallaventura.pe/santaanita/wp-content/uploads/sites/2/2019/09/check-verde.png" alt="check" class="check-image">
    </div>
    <div class="contenedor-texto text-center ">
      <h3 class="p-3"> Felicitaciones!</h3>
      <% if Cart.last.cart_items.count > 1 %>
        <p class="salvado"> Salvaste
          <strong> <%= Cart.last.cart_items.count %> platones </strong>
        </p>
      <% else %>
        <p> Salvaste
        <strong> <%= Cart.last.cart_items.count %> platón</strong>
        </p>
      <% end %>
      <p> Y ahorraste  <strong>$ <%= (Cart.last.total/2) %></strong>
      <p class="lead text-center">
        <a class="botoncitooo btn btn-primary btn-lg rounded" href="/shops" role="button">Volver al inicio</a>
      </p>
    </div>
  </div>
</div>

app/views/pages/dashboard.html.erb
<div class=" container ">
  <h1 class="m-5 text-center">¡Bienvenido <%= @shop.name %>!</h1>
  <div class="row"> 
    <div class="col-12 col-md-6">
      <h3 class="text-center mb-4">Tus pedidos de hoy</h3>
      <div class="table-responsive">
        <table class="table table-striped table-hover table-primary">
          <thead class="thead-green">
            <tr>
              <th scope="col">Cliente </th>
              <th scope="col">Telefono</th>
              <th scope="col">Pedido</th>
              <th scope="col">Total</th>
              <th scope="col">Status</th>
            </tr>
          </thead>
          <tbody>
            <% @carts.each do |cart| %>
              <tr>
              <td class="m-2"> <%= cart.user.first_name%> </td>
              <td class="px-2"><%= cart.user.phone_number %></td>
                <td>
                  <% cart.cart_items.each do |item|%>
                  <ul class="px-2"> <%= item.quantity %> - <%= item.product.name %> </ul>
                  <% end %>
                </td>
                <td><%= cart.total %></td>
                <td>
                  <% if cart.delivery_status == "pendiente" %>
                    <%= simple_form_for cart do |f| %>
                      <%= f.button :submit, "Confirmar", class:"btn btn-info m-2", required: false %>
                    <% end %>
                  <% else %>
                    <p>Entregado</p>
                  <% end %>
                </td> 
              </tr>
            <% end %>
          </tbody>
        </table>
      </div>

    </div>
    
    <div class="col-12 col-md-6">
      <h3 class="text-center mb-4">Tus productos
        <%= link_to "+ Agregar producto", new_product_path, class:"btn btn-primary  rounded" %>
      </h3>
      <div class="d-flex flex-column align-items-center ">
        <% @products.each do |product|%>
        
          <div class="card-product">
            <%= cl_image_tag product.photo.key, crop: :fill %>
            <div class="card-product-infos d-flex flex-column justify-content-between">
              <div class="d-flex justify-content-between">
                <div>
                  <h2><%= product.name %></h2>
                  <p><%= product.description %></p>
                </div>
                <div class="d-flex flex-column">
                  <span class="price-product">$ <%= product.previous_price %></span>
                  <span class="offer-product">$<%= product.unit_price %></span>
                </div>
              </div>
              <div class="text-center">
                <%= link_to "Editar producto", edit_product_path(product), class:"btn btn-info" %>
                <%= link_to "Eliminar producto", product_path(product), method: :delete, class:"btn btn-primary" %>
              </div>
            </div>
          </div>
        <% end %>  
      </div>
    </div>
  </div>
</div>

app/views/pages/home.html.erb
<%= render 'shared/banner' %>

<div class="container-fluid bg-white separte ">
  <h1 class="text-center pt-5">¡Sé parte del cambio!</h1>
  <div class="row d-flex justify-content-center bg-white width-100 ">
    <div class="exp-card col-6 col-md-4 d-flex justify-content-center bg- rounded">
      <div>
        <div class="d-flex justify-content-center">
          <%= cl_image_tag("basura", crop: :fill, class:"mt-4 thumbnail") %>
        </div>
        <div class="p-2 text-center d-flex justify-content-center">
          <p class="pe">En la Argentina se desechan 16 millones<br>de toneladas de alimentos por año.</p>
        </div>
      </div>
    </div>
    <div class="exp-card col-6 col-md-4 d-flex justify-content-center bg-white rounded">
      <div>
        <div class="d-flex justify-content-center">
          <%= cl_image_tag("plantasmano",  crop: :fill, class:"mt-4 thumbnail") %>
        </div>
        <div class="p-2 text-center d-flex justify-content-center">
          <p class="pe">Decidimos aportar nuestro granito de<br>arena en para combatir el desperdicio de alimento.</p>
        </div>
      </div>
    </div>
    <div class="exp-card col-6 col-md-4 d-flex justify-content-center bg-white rounded">
      <div>
        <div class="d-flex justify-content-center">
          <%= cl_image_tag("tercera", crop: :fill, class:"mt-4 thumbnail") %>
        </div>
        <div class="p-2 text-center d-flex justify-content-center">
          <p class="pe"> Unite a nosotros, disfrutá de nuestros descuentos<br>y salvemos al planeta juntos.</p>
        </div>
      </div>
    </div>
  </div>
</div>

<%# LOGROS PLATONICOS %>
<div class="container-fluid row align-items-center" >
  <div class="col-sm-12 col-md-6">
    <div class="content-box rounded platonicos">
      <h2 class="text-center text-dark mt-4">LOGROS PLATÓNICOS </h2>
      <div class="container text-dark">
        <div class="row text-center d-flex justify-content-center">
          <div class="border-right col-6 col-md-4 ">
            <div class="stat-items">
              <i class="fas fa-utensils"></i>
              <h2><span class="counter text-center text-primary "><%=" #{@cart_items.count}"%> + </span> </h2>
              <h4><strong>Platones Salvados</strong></h4>
            </div>
          </div>
          <div class="col-6 col-md-4 ">
            <div class="stat-items">
              <i class="far fa-money-bill-alt"></i>
              <% @cart_items.each do |item| %>
                <% @total+=item.subtotal_price %>
              <% end %>
              <h2><span class="counter text-center text-primary"> $<%= @total/2 %> </span></h2>
              <h4><strong> Ahorrados </strong></h4>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>

<%# FOTO DE LA MINA CON LAS COMPRASSSSSSSS %>
  <div class="col-sm-12 col-md-6">
    <div class="d-flex justify-content-center">
      <%= cl_image_tag("compras", height:500, width:300, class:"waste") %>
    </div>
  </div>
</div>

<%# COMO PEDIR !!!!!!!!!!! %>
<div class="container-fluid p-4 containerverde">
  <div class="container pb-4  ">
    <h1 class=" titulo_div_verde text-center pb-4 text-white">¿Cómo pedir?</h1>
    <div class="row d-flex justify-content-center">
      <div class="exp-card col-6 col-md-4 d-flex justify-content-center">
        <div>
          <div class="d-flex justify-content-center">
            <%= cl_image_tag("buscarlocal1", crop: :fill, class:"thumbnail") %>
          </div>
          <div>
            <h4 class="titulo_div_verde mt-4 text-center text-white">1.Ubicá</h4>
            <p class="explicacion text-white">Encontrá tus comercios cercanos</p>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-4 d-flex justify-content-center exp-card">
        <div>
          <div class="d-flex justify-content-center">
            <%= cl_image_tag("carritoooo" , crop: :fill, class:"thumbnail") %>
          </div>
          <div>
            <h4 class=" titulo_div_verde mt-4 text-center text-white">2.Elegí</h4>
            <p class="explicacion text-white">Seleccioná tus platos favoritos</p>
          </div>
        </div>
      </div>
      <div class="col-6 col-md-4 d-flex justify-content-center exp-card">
      <div>
          <div class="d-flex justify-content-center">
            <%= cl_image_tag("shopp",  crop: :fill, class:"thumbnail") %>
          </div>
          <div>
            <h4 class=" titulo_div_verde mt-4 text-center text-white">3.Retirá</h4>
            <p class="explicacion text-white" >Disfrutá de la mejor comida al mejor precio</p>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

<%# DESTACADOS %>
<div class="destacados p-2 ">
  <div class="container p-4">
  <h1 class="text-center pb-4 text-white">Restaurants destacados</h1>
    <div class="cards d-flex justify-content-center">
      <% @destacados.each do |shop| %>
      <%= link_to shop_path(shop), class:"card_product" do %>
        <div class="card-img-top position-relative">
          <div class="heart">
            <i class="fas fa-heart"></i>
          </div>
          <% if shop.photo.attached? %>
              <%= cl_image_tag shop.photo.key, height:300, width:300, crop: :fill %>
          <% else %>
            <%= cl_image_tag("mojito_baggco", height:300, width:300, crop: :fill) %>
          <% end %>
        </div>
        <div class="p-3">
          <div class="rating">
            <% if shop.rating.nil? %>
              <% 5.times do %>
                <i class="far fa-star"></i>
              <% end %>
            <% else %>
              <% shop.rating.times do  %>
                <i class="fas fa-star"></i>
              <% end %>
              <% (5 - shop.rating).times do %>
                <i class="far fa-star"></i>
              <% end %>
            <% end %>
          </div>
          <h4><%= shop.name %></h4>
          <p class="small m-0"><%= shop.address %></p>
        </div>
      <% end %>
      <% end %>
    </div>
    <div class="text-center p-4">
      <%= link_to "Ver más", shops_path,  class:"btn btn-lg btn-primary rounded"%>
    </div>
  </div>
  </div>
</div>

app/views/pages/summary.html.erb
<div class="container table-responsive">
  <h1 class="text-center">Total en ventas: $  <%= get_carts_total(@carts) %></h1>
  <table class="table table-striped table-hover table-primary">
    <thead class="thead-green">
      <tr>
        <th scope="col">Cliente </th>
        <th scope="col">Pedido</th>
        <th scope="col">Total</th>
      </tr>
    </thead>
    <tbody>
      <% @carts.each do |cart| %>
        <tr>
          <td class="m-2"> <%= "#{cart.user.first_name.capitalize} #{cart.user.last_name.capitalize}"%> </td>
          <td>
            <% cart.cart_items.each do |item|%>
            <ul class="px-2"> <%= item.quantity %> - <%= item.product.name %> </ul>
            <% end %>
          </td>
          <td class="px-2"> $ <%= cart.total %></td>
        </tr>
      <% end %>
        <tr>
        <td><%= current_user.shop.name %></td>
        <td>Total en ventas</td>
        <td>$ <%= get_carts_total(@carts) %></td>
        </tr>
    </tbody>
  </table>
</div>