config/routes.rb
Rails.application.routes.draw do
  get 'deliveries/create'
  root to: 'pages#home'
  get '/pages/confirmation', to: 'pages#confirmation', as: "confirmation"
  devise_for :users
  get '/dashboard', to: 'pages#dashboard'
  get '/summary', to: 'pages#summary'
  resources :shops
  resources :products, only: [:update, :edit, :destroy, :new, :create] do
    resources :cart_items, only: [:create]
  end  
  resources :cart_items, only: [:update, :destroy] do
    member do
      patch "increase"
    end
  end
  resources :carts, only: [:show, :update] do
    resources :deliveries, only: :create # patch "/increase", 
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/cart.rb
class Cart < ApplicationRecord
  enum delivery_status: {pendiente: 0, entregado: 1}
  belongs_to :user
  belongs_to :shop
  has_many :cart_items, dependent: :destroy
  has_many :products, through: :cart_items

  def total
    cart_items.sum do |item|
      item.subtotal_price * item.quantity
    end
  end

  def number_of_items
    cart_items.count
  end

  def has_items?
    number_of_items > 0
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  
  def show
    @cart = Cart.find(params[:id])
    @cart_items = CartItem.all
    # @products = Product.all
    # @products.each do |product|
    #   if  product.name == @cart_items.product.name
    #     @cart_item.quantity += 1
    #   end
    # end
    
    authorize @cart
  end

  def update
    @cart = Cart.find(params[:id])
    authorize @cart
    if @cart.shop.user_id == current_user.id
      @cart.update(delivery_status: 1) 
      redirect_to dashboard_path
      return
    else
      @cart.update(submited_at: Time.current)
      redirect_to confirmation_path
    end  
  end

end

app/views/carts/show.html.erb
<div id="generic_price_table" class="bg-white" >   
<section>
        <div class="container">  
            <div class="row">
                <div class="col-md-12">
                    <div class="generic_content clearfix">
                        <div class="generic_head_price clearfix">
                            <div class="generic_head_content clearfix">
                                <div class="head_bg"></div>
                                <div class="head">
                                    <span>Tu pedido </span>
                                </div>
                            </div>
                            <div class="generic_price_tag clearfix">	
                                <span class="price">
                                    <span class="sign">Precio total : </span>
                                    <span class="sign">$ </span>
                                    <span class="currency"> <%= @cart.total  %></span>
                                    <br>
                                    <span class="cent">Tus productos:</span>
                                </span>
                            </div>
                        </div>                            
                        <div class="generic_feature_list">
                          <% @cart.cart_items.each do |item| %>
                            <ul>
                                <li>
                                  <span class="grandecito"><%= item.quantity%></span>
                                  <span class="grandecito"><%=item.product.name%></span>
                                  <span class="grandecito" >$ <%= item.quantity*item.subtotal_price %> </span>
                                  <span class="ml-4">
                                    <%= link_to cart_item_path(item), method: :delete, data:{confirm:"Quiere eliminarlo?"} do %>
                                    <p class="far fa-trash-alt"></p> <% end %>
                                  </span>
                                </li>
                              </ul>
                            <%end  %>
                        </div>
                        <div class="generic_price_btn clearfix">
                        	 <div class="text-center m-4 bg-red">
                              <% if @cart.cart_items.count > 1 %>
                                <p id="separador"> Estas salvando: 
                                <strong> <%= @cart.cart_items.count %> platones</strong>
                                </p>
                              <% else %>
                                <p> Estas salvando: 
                                <strong> <%= @cart.cart_items.count %> platón</strong>
                                </p>
                              <% end %>
                              <p> Y ahorrando: <strong>$ <%= (@cart.total/2) %></strong>
                              </p>
                            </div>
                            <div class="text-center">
                              <%= simple_form_for @cart do |f| %>
                                <%= f.button :submit, "Realizar compra", class:"fas fa-shopping-cart btn btn-lg btn-primary rounded p-3" %>
                              <% end %>
                            </div>
                        </div>     
                    </div>   
                </div>
            </div>	
        </div>
</section>             
</div>